<?php
session_start();

// --- Configuration ---
$config_file = '/opt/sla_monitor/sla_config.env';

function load_config($file_path) {
    if (!file_exists($file_path)) return [];
    $lines = file($file_path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    $config = [];
    foreach ($lines as $line) {
        if (strpos(trim($line), '#') === 0) continue;
        list($key, $value) = explode('=', $line, 2);
        $config[trim($key)] = trim($value);
    }
    return $config;
}

$config = load_config($config_file);
$stored_username = $config['DASHBOARD_USERNAME'] ?? 'admin';
// IMPORTANT: This hash should be generated by a setup script.
// Example for password 'admin': password_hash('admin', PASSWORD_DEFAULT)
$stored_password_hash = $config['DASHBOARD_PASSWORD_HASH'] ?? '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'; // Default: 'password'

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $username = $_POST['username'] ?? '';
    $password = $_POST['password'] ?? '';

    if ($username === $stored_username && password_verify($password, $stored_password_hash)) {
        // Regenerate session ID to prevent session fixation
        session_regenerate_id(true);
        $_SESSION['loggedin'] = true;
        header('Location: index.html');
        exit;
    } else {
        header('Location: login.html?error=Invalid credentials');
        exit;
    }
} else {
    header('Location: login.html');
    exit;
}
?>