version: '3.8'

services:
  sla_monitor_central_app:
    build:
      context: ./central_server_package 
      dockerfile: Dockerfile
    container_name: sla_monitor_central_app
    restart: unless-stopped
    ports:
      - "80:80" 
      # - "443:443" # Uncomment when you set up SSL, likely via a reverse proxy
    volumes:
      # Mount the directory for SQLite DB and general config (from host to container)
      # Ensure these host paths exist or are created before first 'docker-compose up'
      # The container will need appropriate permissions to write to these if it creates files.
      # It's often best to initialize the DB and config on the host first.
      - ./data/central_server_opt_sla_monitor:/opt/sla_monitor 
      # Mount API log directory (PHP scripts need to be configured to log here, or log to stdout)
      - ./logs/central_api:/var/log/sla_app_logs 
      # Mount Apache logs from container to host for easier access
      - ./logs/central_apache:/var/log/apache2
    environment:
      # Ensures Apache logs to stdout/stderr so `docker logs` can pick them up
      APACHE_LOG_DIR: /var/log/apache2 
      # You can pass other environment variables here if needed by your PHP scripts
      # e.g., SQLITE_DB_PATH_IN_CONTAINER: /opt/sla_monitor/central_sla_data.sqlite
      #      CONFIG_FILE_PATH_IN_CONTAINER: /opt/sla_monitor/sla_config.env

# Optional: Define named volumes if you prefer them over host bind mounts for data
# volumes:
#   central_opt_sla_monitor_data:
#   central_api_logs_data:
#   central_apache_logs_data: