version: '3.8'

services:
  sla_monitor_central_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sla_monitor_central_app
    restart: unless-stopped
    ports:
      # CHANGED: The host port is now 8080, which maps to port 80 inside the container.
      - "8080:80"
      # CHANGED: The host port is now 8443, which maps to port 443 inside the container.
      - "8443:443"
    volumes:
      # These volume paths are correct and do not need to be changed.
      - /srv/sla_monitor/central_app_data/opt_sla_monitor:/opt/sla_monitor
      - /srv/sla_monitor/central_app_data/apache_logs:/var/log/apache2
      - /srv/sla_monitor/central_app_data/api_logs/sla_api.log:/var/log/sla_api.log
    environment:
      # This is correct and does not need to be changed.
      APACHE_LOG_DIR: /var/log/apache2